name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Express Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd "BTWBeheer application"
          cd server
          docker build -t midasnies/btwbeheer-express-app:${{ github.sha }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push midasnies/btwbeheer-express-app:${{ github.sha }}

      - name: Build and push React Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd "BTWBeheer application"
          cd client
          docker build -t midasnies/btwbeheer-react-app:${{ github.sha }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push midasnies/btwbeheer-react-app:${{ github.sha }}
