name: Run Unit Tests

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger tests on

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.TEST_DB_HOST }}
      PORT: ${{ secrets.EXPRESS_PORT }}
      DB_USER: ${{ secrets.TEST_DB_USER }}
      DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.TEST_DB_NAME }}
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change this to the Node.js version you're using

    - name: Install dependencies
      working-directory: ./BTWBeheer application/server  # Specify the folder path
      run: npm install

    - name: Run Unit Tests
      working-directory: ./BTWBeheer application/server  # Specify the folder path
      run: npm run test:unit  # Adjust the script name as needed
